# Generated by Django 3.2.4 on 2021-08-01 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('horse_power', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('description', models.TextField()),
                ('color', models.CharField(choices=[('BL', 'Black'), ('RD', 'Red'), ('WH', 'White'), ('OT', 'Other')], default='BL', max_length=2)),
                ('transmision', models.CharField(choices=[('MA', 'Manual'), ('AU', 'Automatic')], default='MA', max_length=2)),
                ('body_type', models.CharField(choices=[('CP', 'Coupe'), ('HB', 'Hatchback'), ('CB', 'Cabrio'), ('SD', 'Sedan'), ('WG', 'Wagon'), ('SV', 'SUV'), ('VN', 'Van')], default='CP', max_length=2)),
                ('fuel_type', models.CharField(choices=[('DI', 'Diesel'), ('GA', 'Gasoline'), ('EL', 'Electric'), ('HY', 'Plug-in Hybrid')], default='DI', max_length=2)),
                ('image', models.ImageField(upload_to='car_pics/')),
                ('price', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
