# Generated by Django 3.2.4 on 2021-08-02 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dealership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='favourites',
            field=models.ManyToManyField(related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
